# Generated by Django 4.1.5 on 2023-01-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_products_p_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
