# Generated by Django 4.1.5 on 2023-01-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_logged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pswd', models.CharField(max_length=50)),
            ],
        ),
    ]
